name: appstream
version: 0.2.1

description:
  A parser for Appstream data.
  This package allows Dart applications to access package metadata on Linux systems.

homepage: https://github.com/canonical/appstream.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  xml: ^5.1.1
  yaml: ^3.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.8
